Document: gnome-network-displays
Title: Debian gnome-network-displays Manual
Author: <insert document author here>
Abstract: This manual describes what gnome-network-displays is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gnome-network-displays/gnome-network-displays.sgml.gz

Format: postscript
Files: /usr/share/doc/gnome-network-displays/gnome-network-displays.ps.gz

Format: text
Files: /usr/share/doc/gnome-network-displays/gnome-network-displays.text.gz

Format: HTML
Index: /usr/share/doc/gnome-network-displays/html/index.html
Files: /usr/share/doc/gnome-network-displays/html/*.html
